# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksNAOSdp9WH5yYaAjetjqFGNA6Iaz-78
"""

# -- coding: utf-8 --
"""car_mileage_app.py"""

import streamlit as st
import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

warnings.filterwarnings("ignore")

# App Title and Description
st.set_page_config(page_title="Car Mileage Predictor")
st.title("🚗 Car Mileage Predictor")
st.markdown("Upload car data, select features, and predict mileage (MPG) using ML models.")

# Load Data
@st.cache_data
def load_data():
    df = pd.read_csv("Car Data India.csv")
    df.columns = [col.lower().strip() for col in df.columns]
    return df

df = load_data()

# Sidebar column info
st.sidebar.header("📋 Column Info")
st.sidebar.write(df.columns.tolist())

# Feature selection
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
target_col = 'mileage'

# Remove target column from features
if target_col in numeric_cols:
    numeric_cols.remove(target_col)

# Feature selection from user
st.markdown("<h3 style='color:white;'>🧮 Feature Selection</h3>", unsafe_allow_html=True)
selected_features = st.multiselect("Choose features for prediction:", numeric_cols)

# Model selection
st.markdown("<h5 style='color:white;'>📌 Select Model</h5>", unsafe_allow_html=True)
model_type = st.radio("", ["Linear Regression", "Random Forest"])

# Main ML logic
if selected_features:
    df = df.dropna(subset=[target_col])

    X = df[selected_features]
    y = df[target_col]

    # Split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Preprocessing pipeline
    numeric_transformer = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    preprocessor = ColumnTransformer([
        ('num', numeric_transformer, selected_features)
    ])

    # Choose model
    if model_type == "Linear Regression":
        model = Pipeline([
            ('preprocessor', preprocessor),
            ('regressor', LinearRegression())
        ])
    else:
        model = Pipeline([
            ('preprocessor', preprocessor),
            ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
        ])

    model.fit(X_train, y_train)

    # Manual Input
    st.markdown("<h3 style='color:white;'>📝 Predict Mileage for a New Car</h3>", unsafe_allow_html=True)
    user_input = {}

    for feature in selected_features:
        user_input[feature] = st.number_input(f"Enter {feature}", min_value=0.0)

    if st.button("Predict Mileage"):
        input_df = pd.DataFrame([user_input])
        prediction = model.predict(input_df)[0]
        st.success(f"Predicted Mileage (MPG): {prediction:.2f}")
else:
    st.warning("Select at least one feature to proceed.")