# -*- coding: utf-8 -*-
"""car.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5KqdnofaRTkCouBeJSlOLy_w4EQxO0v
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df = pd.read_csv('/content/Car Data India.csv')
df.head()

data = df[['Engine_CC', 'Year', 'Price', 'Mileage']]
data = data.dropna()

X = data[['Engine_CC', 'Year', 'Price']]
y = data['Mileage']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

new_car = [[1500, 2020, 1000000]]
predicted_mileage = model.predict(new_car)
print("Predicted Mileage:", predicted_mileage[0])

